trigger:
  - master

pool:
  vmImage: 'windows-2019'

steps:
  - script: yarn install
    displayName: Install dependencies
  - script: yarn run electron:build
    displayName: Build app
  - task: PublishBuildArtifacts@1
    displayName: Publish artifacts
    inputs:
      pathtoPublish: $(Build.SourcesDirectory)/dist_electron
      artifactName: artifacts-$(Build.BuildId)
      publishLocation: Container
