trigger:
  - master

pool:
  vmImage: 'windows-2019'

steps:
  - script: yarn install
    displayName: Install dependencies
  - script: yarn run electron:build
    displayName: Build app
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)/dist_electron
      artifactName: drop
      publishLocation: Container
